version: "3"
services:

        redis:
                image: redis:alpine
                ports:
                        - "6379"
                networks:
                        - demonet
                deploy:
                  replicas: 1
        pipelinedemo:
                image: anilskp/pipelinedemo:latest
                ports:
                        - "8005:5000"
                networks:
                        - demonet
                deploy:
                        replicas: 3
networks:
        demonet:
                driver: overlay
